#######################################################
#
# BiddingStrategy.py
# Python implementation of the Interface BiddingStrategyInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: Arash Ebrahimnezhad
#
#######################################################
from core.Bid import Bid
from abc import ABC, abstractmethod
from core.TimeLine import TimeLine


class BiddingStrategyInterface(ABC):

    @abstractmethod
    def send_bid(self, timeline: TimeLine) -> Bid:
        raise NotImplementedError()
