#######################################################
#
# NegoTable.py
# Python implementation of the Class NegoTable
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: Arash Ebrahimnezhad
#
#######################################################
from core.Offer import Offer
from core.StateInfo import StateInfo
from core.NegoPartyInterface import NegoPartyInterface


class NegoTable:

    def __init__(self, parties: tuple, state_info: StateInfo):
        """
        In initializing of AbstractProtocol a data structure will be created
        in order to show offers_on_the_table. an example of this data structure was shown in the following:
        {party1:[offer1, offer2, ...], party2:[offer1, offer2, ...], ...}
        :param parties: tuple of NegoPartyInterface object
        :param state_info:
        """
        if not isinstance(parties, tuple):
            raise TypeError('parties argument must be the tuple (tuple of NegoPartyInterface)!')
        for party in parties:
            if not isinstance(party, NegoPartyInterface):
                raise TypeError('parties argument must be the tuple of NegoPartyInterface!')
        if not isinstance(state_info, StateInfo):
            raise TypeError('state_info argument must be instance of StateInfo!')

        self.__parties = parties
        self.__state_info = state_info
        self.__offers_on_the_table = {}
        for party in parties:
            self.__offers_on_the_table[party] = []

    def get_state_info(self) -> StateInfo:
        return self.__state_info

    def get_offers_on_table(self):
        return self.__offers_on_the_table

    def get_parties(self) -> tuple:
        return self.__parties

    def add_offer(self, party: NegoPartyInterface, offer: Offer):
        if not isinstance(party, NegoPartyInterface):
            raise TypeError('party argument must be an instance of NegoPartyInterface')
        if not isinstance(offer, Offer):
            raise TypeError('offer argument must be an instance of Offer')
        self.__offers_on_the_table[party].append(offer)

    def is_table_empty(self) -> bool:
        """
        this method returns True if there is no
        offer on the table and vice versa
        :return: True|False
        """
        for party in self.__parties:
            if self.__offers_on_the_table[party]:
                return False
        return True

