#######################################################
#
# OpponentModel.py
# Python implementation of the Interface OpponentModelInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.Preference import Preference
from core.Offer import Offer
from abc import ABC, abstractmethod


class OpponentModelInterface(ABC):

    @abstractmethod
    def get_initial_opponent_preference(self) -> Preference:
        pass

    @abstractmethod
    def get_preference(self) -> Preference:
        pass

    @abstractmethod
    def update_preference(self, offer: Offer) -> Preference:
        pass
