#######################################################
#
# ProtocolInterface.py
# Python implementation of the Interface ProtocolInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: Arash Ebrahimnezhad (arash.ebrah@gmail.com)
#
#######################################################
from core.TimeLine import TimeLine
from abc import ABC, abstractmethod
import core.NegoPartyInterface as NegoPartyInterface


class ProtocolInterface(ABC):

    @abstractmethod
    def negotiate(self, offers_on_the_table: dict):
        """This method ask a bid from party according to order and negotiation state then
        convert it to offer and add it to the table offers and update negotiation state

           negotiation state will be 1 if the last parties' offer are same
           negotiation state will be 0 if the last parties' offer are not same
           negotiation state will be -1 if the one of last parties' offer's Bid is {}
        """
        raise NotImplementedError()

    @abstractmethod
    def get_offers_on_table(self, party_name: str) -> tuple:
        """This method gets a party name in string type and returns a tuple of offers
        related to the party name that has got through the object that has called the
        method.
           Before returning the offers, the method checks out whether the object that
        has called the method has authority to access the offers or not? if there is no
        permission it returns an error.
        """
        raise NotImplementedError()

    @abstractmethod
    def get_time(self) -> float:
        raise NotImplementedError()

    @abstractmethod
    def get_time_line(self) -> TimeLine:
        raise NotImplementedError()

    @abstractmethod
    def get_parties(self) -> NegoPartyInterface:
        raise NotImplementedError()

    @abstractmethod
    def get_state_info(self):
        raise NotImplementedError()