#######################################################
# 
# TimeLine.py
# Python implementation of the Class TimeLine
# Generated by Enterprise Architect
# Created on:
# Original author: Arash Ebrahimnnezhad
# 
#######################################################
import time


class TimeLine:
    def __init__(self, deadline: float, deadline_type: str):
        if not isinstance(deadline, float):
            raise TypeError('deadline argument must be a float')
        if not isinstance(deadline_type, str):
            raise TypeError('deadline_type argument must be a float')
        self.__nan_to_second = (10 ** 9)
        self.__beginning_time = time.time_ns()
        self.__current_time = time.time_ns()
        self.__deadline = deadline
        self.__deadline_type = deadline_type

    def get_time(self) -> float:
        self.__current_time = time.time_ns()
        return (self.__current_time - self.__beginning_time) / (self.__deadline * self.__nan_to_second)

    def is_time_ended(self):
        """
        :return: True if deadline has been reached
        """
        self.__current_time = time.time_ns()
        if self.__deadline_type == 's':
            deadline = self.__deadline
        elif self.__deadline_type == 'ms':
            deadline = self.__deadline/1000 # convert to ms
        else:
            raise ValueError('deadline_type must be s or ms')
        return ((self.__current_time - self.__beginning_time)/self.__nan_to_second) >= deadline
